name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up JDK 11 (Temurin)
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install docker-ce docker-ce-cli containerd.io

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build and run Docker containers
        run: |
          docker-compose up --build -d
          sleep 30  # Warten bis die Container gestartet sind

      - name: Run tests
        run: |
          docker-compose exec ResourceCalc java -jar /app/ResourCecalc.jar
