name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up JDK 11 (Temurin)
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build and run Docker containers
        run: |
          docker-compose up --build -d
          sleep 30  # Warten bis die Container gestartet sind

      - name: Run tests
        run: |
          docker-compose exec ResourceCalc java -jar /app/cloud-usage.jar
