name: build-push

on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Pull Assessment Docker Image
        run: docker pull mrksdh/assessment

      - name: Install cUrl
        run: |
          sudo apt-get update && sudo apt-get install -y curl

      - name: Create Docker Network
        run: |
          docker network create my_network

      - name: Start Assessment Docker Container
        run: |
          docker run -d --name assessment --network my_network -p 8080:8080 mrksdh/assessment
          sleep 15

      - name: Perform Health Check
        run: |
          curl -f http://localhost:8080/health || exit 1

      - name: Grant Execute Permission for Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Build gradle with shadowJar
        run: |
          ./gradlew clean shadowJar

      - name: Run Java App
        run: |
          # Capture output from the Java app
          output=$(java -jar build/libs/*.jar)
          echo "$output"
           # Extract the status code from the output
          status_code=$(echo "$output" | grep -oP '"code":[0-9]*' | cut -d ":" -f 2)

          # Output the status code to the environment
          echo "status_code=$status_code" >> $GITHUB_ENV

          # Check if the status code is 200
          if [ "$status_code" != "200" ]; then
            echo "Status code not found or is not 200, exiting with error."
            exit 1
          fi